### ISSUE TITLE
Generate a my-nav Component

### ISSUE THREAD

**Issue by web-dave** [web-dave/angular-essentials-workshop#4]
* Generate a nav component with angular-cli
* Use this new nav component in the appComponent view

**Comment by web-dave** [comment]
<details> <summary>generate</summary>

```sh
ng g c top-nav
```
</details>
<details> <summary>top-nav.component.html</summary>

```html
<ul>
  <li><a class="active" href="#">Books</a></li>
  <li><a href="#">About</a></li>
</ul>
```
</details>
<details> <summary>top-nav.component.scss</summary>

```scss
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
  li {
    float: left;
  }
  a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    &:hover:not(.active) {
      background-color: #111;
    }
    &.active {
      background-color: #4caf50;
    }
  }
}
```
</details>
